pipeline {
    agent {
        docker {
            image 'maven:latest'
            args '-v /root/.m2:/root/.m2'
        }
    }
    stages {
        //use Maven Build
        stage('Clean') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        //use SonarQube
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        //deploy to Nexus Repo
       
        //deploy to TomCat Web Server
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }

    }
}
